// Test generated by RoostGPT for test ReactStoryBook using AI Type Open AI and AI Model gpt-4

import '@testing-library/jest-dom'
import { setGlobalConfig } from '@storybook/testing-react'
import { getWorker } from 'msw-storybook-addon'
import * as globalStorybookConfig from '../.storybook/preview'

setGlobalConfig(globalStorybookConfig)

describe("Test getWorker close method", () => {
  let worker;

  beforeAll(() => {
    worker = getWorker();
  });

  test("getWorker returns an object", () => {
    expect(typeof worker).toBe("object");
  });

  test("getWorker object has close method", () => {
    expect(worker).toHaveProperty("close");
    expect(typeof worker.close).toBe("function");
  });

  test("close method executes without error", () => {
    expect(() => {
      worker.close();
    }).not.toThrow();
  });

  afterAll(() => {
    worker = null;
  });
});
