// Test generated by RoostGPT for test ReactStoryBook using AI Type Open AI and AI Model gpt-4

import { suite } from 'uvu';
import * as assert from 'uvu/assert';
import { setGlobalConfig } from '@storybook/testing-react';
import { getWorker } from 'msw-storybook-addon';
import globalStorybookConfig from '../.storybook/preview';

// Set global configuration for @storybook/testing-react
setGlobalConfig(globalStorybookConfig);

let worker;

suite('Testing getWorker close method', () => {

  suite.before.each(() => {
    // Get the worker instance before running the tests
    worker = getWorker();
  });

  suite('worker exists', () => {
    // Test to check if the worker exists
    assert.type(worker, 'object');
  });

  suite('worker close method', () => {
    // Mock the close method
    let mockClose = false;
    worker.close = () => { mockClose = true };

    // Call the method to be tested
    suite.after.each(() => worker.close());

    // Test if the close method was called
    assert.is(mockClose, true);
  });

  suite('worker close method not called before afterAll', () => {
    // Mock the close method
    let mockClose = false;
    worker.close = () => { mockClose = true };

    // Test if the close method was not called before afterAll
    assert.is(mockClose, false);
  });

}).run();
